spring.application.name=smartlocck

app.config.id=${MINHA_VARIAVEL1:ABC}
app.config.secret=${MINHA_VARIAVEL2:DEF}

app.config.url=http://192.168.0.15:3001


spring.mongodb.authentication-database=admin
spring.mongodb.auto-index-creation=true
spring.mongodb.host=localhost
spring.mongodb.port=27017
spring.mongodb.database=smartstockdb
spring.mongodb.username=adm
spring.mongodb.password=123